window.GRADE4_KANJI = [
  { kanji: "愛", order: 1, writeKana: "あいじょう", writeAnswer: "愛情", readWord: "愛鳥", readAnswer: "あいちょう" },
  { kanji: "案", order: 2, writeKana: "あんない", writeAnswer: "案内", readWord: "名案", readAnswer: "めいあん" },
  { kanji: "以", order: 3, writeKana: "いじょう", writeAnswer: "以上", readWord: "以内", readAnswer: "いない" },
  { kanji: "衣", order: 4, writeKana: "いふく", writeAnswer: "衣服", readWord: "雨衣", readAnswer: "あまごい" },
  { kanji: "位", order: 5, writeKana: "じゅんい", writeAnswer: "順位", readWord: "第一位", readAnswer: "だいいちい" },
  { kanji: "囲", order: 6, writeKana: "はんい", writeAnswer: "範囲", readWord: "囲む", readAnswer: "かこむ", okuriPrompt: "かこむ", okuriAnswer: "囲む" },
  { kanji: "胃", order: 7, writeKana: "いえき", writeAnswer: "胃液", readWord: "胃腸", readAnswer: "いちょう" },
  { kanji: "印", order: 8, writeKana: "いんさつ", writeAnswer: "印刷", readWord: "目印", readAnswer: "めじるし", okuriPrompt: "めじるし", okuriAnswer: "目印" },
  { kanji: "英", order: 9, writeKana: "えいご", writeAnswer: "英語", readWord: "英雄", readAnswer: "えいゆう" },
  { kanji: "栄", order: 10, writeKana: "はんえい", writeAnswer: "繁栄", readWord: "栄える", readAnswer: "さかえる", okuriPrompt: "さかえる", okuriAnswer: "栄える" },
  { kanji: "塩", order: 11, writeKana: "しおみず", writeAnswer: "塩水", readWord: "食塩", readAnswer: "しょくえん" },
  { kanji: "億", order: 12, writeKana: "おくまん", writeAnswer: "億万", readWord: "一億", readAnswer: "いちおく" },
  { kanji: "加", order: 13, writeKana: "さんか", writeAnswer: "参加", readWord: "追加", readAnswer: "ついか" },
  { kanji: "果", order: 14, writeKana: "けっか", writeAnswer: "結果", readWord: "青果", readAnswer: "せいか" },
  { kanji: "貨", order: 15, writeKana: "かもつ", writeAnswer: "貨物", readWord: "通貨", readAnswer: "つうか" },
  { kanji: "課", order: 16, writeKana: "かだい", writeAnswer: "課題", readWord: "日課", readAnswer: "にっか" },
  { kanji: "芽", order: 17, writeKana: "はつが", writeAnswer: "発芽", readWord: "新芽", readAnswer: "しんめ" },
  { kanji: "改", order: 18, writeKana: "かいぜん", writeAnswer: "改善", readWord: "改まる", readAnswer: "あらたまる", okuriPrompt: "あらためる", okuriAnswer: "改める" },
  { kanji: "械", order: 19, writeKana: "きかい", writeAnswer: "機械", readWord: "器械", readAnswer: "きかい" },
  { kanji: "害", order: 20, writeKana: "ひがい", writeAnswer: "被害", readWord: "公害", readAnswer: "こうがい" },
  { kanji: "街", order: 21, writeKana: "しょうてんがい", writeAnswer: "商店街", readWord: "街角", readAnswer: "まちかど" },
  { kanji: "各", order: 22, writeKana: "かくち", writeAnswer: "各地", readWord: "各自", readAnswer: "かくじ" },
  { kanji: "覚", order: 23, writeKana: "かんかく", writeAnswer: "感覚", readWord: "目覚める", readAnswer: "めざめる", okuriPrompt: "おぼえる", okuriAnswer: "覚える" },
  { kanji: "完", order: 24, writeKana: "かんせい", writeAnswer: "完成", readWord: "完全", readAnswer: "かんぜん" },
  { kanji: "官", order: 25, writeKana: "けいさつかん", writeAnswer: "警察官", readWord: "官公署", readAnswer: "かんこうしょ" },
  { kanji: "管", order: 26, writeKana: "ほかん", writeAnswer: "保管", readWord: "水道管", readAnswer: "すいどうかん" },
  { kanji: "関", order: 27, writeKana: "かんけい", writeAnswer: "関係", readWord: "関心", readAnswer: "かんしん", okuriPrompt: "せき", okuriAnswer: "関" },
  { kanji: "観", order: 28, writeKana: "かんこう", writeAnswer: "観光", readWord: "観点", readAnswer: "かんてん" },
  { kanji: "願", order: 29, writeKana: "ねがいごと", writeAnswer: "願い事", readWord: "願書", readAnswer: "がんしょ", okuriPrompt: "ねがう", okuriAnswer: "願う" },
  { kanji: "希", order: 30, writeKana: "きぼう", writeAnswer: "希望", readWord: "希少", readAnswer: "きしょう" },
  { kanji: "季", order: 31, writeKana: "しき", writeAnswer: "四季", readWord: "季節", readAnswer: "きせつ" },
  { kanji: "紀", order: 32, writeKana: "せいき", writeAnswer: "世紀", readWord: "紀元", readAnswer: "きげん" },
  { kanji: "喜", order: 33, writeKana: "よろこび", writeAnswer: "喜び", readWord: "喜劇", readAnswer: "きげき", okuriPrompt: "よろこぶ", okuriAnswer: "喜ぶ" },
  { kanji: "旗", order: 34, writeKana: "はたじるし", writeAnswer: "旗印", readWord: "国旗", readAnswer: "こっき" },
  { kanji: "器", order: 35, writeKana: "しょっき", writeAnswer: "食器", readWord: "楽器", readAnswer: "がっき" },
  { kanji: "機", order: 36, writeKana: "ひこうき", writeAnswer: "飛行機", readWord: "機会", readAnswer: "きかい" },
  { kanji: "議", order: 37, writeKana: "かいぎ", writeAnswer: "会議", readWord: "議長", readAnswer: "ぎちょう" },
  { kanji: "求", order: 38, writeKana: "きゅうじん", writeAnswer: "求人", readWord: "要求", readAnswer: "ようきゅう", okuriPrompt: "もとめる", okuriAnswer: "求める" },
  { kanji: "泣", order: 39, writeKana: "なきごえ", writeAnswer: "泣き声", readWord: "泣く", readAnswer: "なく", okuriPrompt: "なく", okuriAnswer: "泣く" },
  { kanji: "救", order: 40, writeKana: "きゅうきゅうしゃ", writeAnswer: "救急車", readWord: "救助", readAnswer: "きゅうじょ", okuriPrompt: "すくう", okuriAnswer: "救う" },
  { kanji: "給", order: 41, writeKana: "きゅうしょく", writeAnswer: "給食", readWord: "配給", readAnswer: "はいきゅう" },
  { kanji: "挙", order: 42, writeKana: "せんきょ", writeAnswer: "選挙", readWord: "挙手", readAnswer: "きょしゅ", okuriPrompt: "あげる", okuriAnswer: "挙げる" },
  { kanji: "漁", order: 43, writeKana: "ぎょぎょう", writeAnswer: "漁業", readWord: "漁船", readAnswer: "ぎょせん" },
  { kanji: "共", order: 44, writeKana: "きょうりょく", writeAnswer: "協力", readWord: "共通", readAnswer: "きょうつう", okuriPrompt: "ともに", okuriAnswer: "共に" },
  { kanji: "協", order: 45, writeKana: "きょうどう", writeAnswer: "共同", readWord: "協会", readAnswer: "きょうかい" },
  { kanji: "鏡", order: 46, writeKana: "てかがみ", writeAnswer: "手鏡", readWord: "眼鏡", readAnswer: "めがね" },
  { kanji: "競", order: 47, writeKana: "きょうそう", writeAnswer: "競争", readWord: "競技", readAnswer: "きょうぎ", okuriPrompt: "きそう", okuriAnswer: "競う" },
  { kanji: "極", order: 48, writeKana: "きょくち", writeAnswer: "極地", readWord: "南極", readAnswer: "なんきょく", okuriPrompt: "きわめる", okuriAnswer: "極める" },
  { kanji: "訓", order: 49, writeKana: "くんれん", writeAnswer: "訓練", readWord: "教訓", readAnswer: "きょうくん" },
  { kanji: "軍", order: 50, writeKana: "ぐんたい", writeAnswer: "軍隊", readWord: "海軍", readAnswer: "かいぐん" },
  { kanji: "郡", order: 51, writeKana: "ぐんぶ", writeAnswer: "郡部", readWord: "郡山", readAnswer: "こおりやま" },
  { kanji: "径", order: 52, writeKana: "はんけい", writeAnswer: "半径", readWord: "直径", readAnswer: "ちょっけい" },
  { kanji: "型", order: 53, writeKana: "もけい", writeAnswer: "模型", readWord: "大型", readAnswer: "おおがた" },
  { kanji: "景", order: 54, writeKana: "ふうけい", writeAnswer: "風景", readWord: "光景", readAnswer: "こうけい" },
  { kanji: "芸", order: 55, writeKana: "こうげい", writeAnswer: "工芸", readWord: "芸名", readAnswer: "げいめい" },
  { kanji: "欠", order: 56, writeKana: "けっせき", writeAnswer: "欠席", readWord: "欠点", readAnswer: "けってん", okuriPrompt: "かける", okuriAnswer: "欠ける" },
  { kanji: "結", order: 57, writeKana: "けっか", writeAnswer: "結果", readWord: "結ぶ", readAnswer: "むすぶ", okuriPrompt: "むすぶ", okuriAnswer: "結ぶ" },
  { kanji: "建", order: 58, writeKana: "けんぶつ", writeAnswer: "建物", readWord: "再建", readAnswer: "さいけん", okuriPrompt: "たてる", okuriAnswer: "建てる" },
  { kanji: "健", order: 59, writeKana: "けんこう", writeAnswer: "健康", readWord: "健全", readAnswer: "けんぜん" },
  { kanji: "験", order: 60, writeKana: "じっけん", writeAnswer: "実験", readWord: "体験", readAnswer: "たいけん" },
  { kanji: "固", order: 61, writeKana: "かたまり", writeAnswer: "固まり", readWord: "固定", readAnswer: "こてい", okuriPrompt: "かためる", okuriAnswer: "固める" },
  { kanji: "功", order: 62, writeKana: "せいこう", writeAnswer: "成功", readWord: "功績", readAnswer: "こうせき" },
  { kanji: "好", order: 63, writeKana: "こうぶつ", writeAnswer: "好物", readWord: "友好", readAnswer: "ゆうこう", okuriPrompt: "このむ", okuriAnswer: "好む" },
  { kanji: "候", order: 64, writeKana: "てんこう", writeAnswer: "天候", readWord: "気候", readAnswer: "きこう" },
  { kanji: "航", order: 65, writeKana: "こうくう", writeAnswer: "航空", readWord: "航海", readAnswer: "こうかい" },
  { kanji: "康", order: 66, writeKana: "けんこう", writeAnswer: "健康", readWord: "小康", readAnswer: "しょうこう" },
  { kanji: "告", order: 67, writeKana: "ほうこく", writeAnswer: "報告", readWord: "広告", readAnswer: "こうこく" },
  { kanji: "差", order: 68, writeKana: "さがく", writeAnswer: "差額", readWord: "時差", readAnswer: "じさ", okuriPrompt: "さす", okuriAnswer: "差す" },
  { kanji: "菜", order: 69, writeKana: "やさい", writeAnswer: "野菜", readWord: "菜園", readAnswer: "さいえん" },
  { kanji: "最", order: 70, writeKana: "さいこう", writeAnswer: "最高", readWord: "最初", readAnswer: "さいしょ" },
  { kanji: "材", order: 71, writeKana: "きざい", writeAnswer: "機材", readWord: "木材", readAnswer: "もくざい" },
  { kanji: "昨", order: 72, writeKana: "さくねん", writeAnswer: "昨年", readWord: "昨夜", readAnswer: "さくや" },
  { kanji: "札", order: 73, writeKana: "さつたば", writeAnswer: "札束", readWord: "名札", readAnswer: "なふだ" },
  { kanji: "刷", order: 74, writeKana: "いんさつ", writeAnswer: "印刷", readWord: "刷る", readAnswer: "する", okuriPrompt: "する", okuriAnswer: "刷る" },
  { kanji: "殺", order: 75, writeKana: "ひっさつ", writeAnswer: "必殺", readWord: "相殺", readAnswer: "そうさい", okuriPrompt: "ころす", okuriAnswer: "殺す" },
  { kanji: "察", order: 76, writeKana: "かんさつ", writeAnswer: "観察", readWord: "警察", readAnswer: "けいさつ" },
  { kanji: "参", order: 77, writeKana: "さんか", writeAnswer: "参加", readWord: "参考", readAnswer: "さんこう", okuriPrompt: "まいる", okuriAnswer: "参る" },
  { kanji: "産", order: 78, writeKana: "さんち", writeAnswer: "産地", readWord: "名産", readAnswer: "めいさん", okuriPrompt: "うむ", okuriAnswer: "産む" },
  { kanji: "散", order: 79, writeKana: "さんぽ", writeAnswer: "散歩", readWord: "解散", readAnswer: "かいさん", okuriPrompt: "ちる", okuriAnswer: "散る" },
  { kanji: "残", order: 80, writeKana: "のこり", writeAnswer: "残り", readWord: "残念", readAnswer: "ざんねん", okuriPrompt: "のこす", okuriAnswer: "残す" },
  { kanji: "士", order: 81, writeKana: "りきし", writeAnswer: "力士", readWord: "兵士", readAnswer: "へいし" },
  { kanji: "氏", order: 82, writeKana: "しめい", writeAnswer: "氏名", readWord: "山田氏", readAnswer: "やまだし" },
  { kanji: "史", order: 83, writeKana: "れきし", writeAnswer: "歴史", readWord: "史上", readAnswer: "しじょう" },
  { kanji: "司", order: 84, writeKana: "しほう", writeAnswer: "司法", readWord: "上司", readAnswer: "じょうし" },
  { kanji: "試", order: 85, writeKana: "しけん", writeAnswer: "試験", readWord: "試合", readAnswer: "しあい", okuriPrompt: "ためす", okuriAnswer: "試す" },
  { kanji: "児", order: 86, writeKana: "ようじ", writeAnswer: "幼児", readWord: "児童", readAnswer: "じどう" },
  { kanji: "治", order: 87, writeKana: "せいじ", writeAnswer: "政治", readWord: "治る", readAnswer: "なおる", okuriPrompt: "なおす", okuriAnswer: "治す" },
  { kanji: "辞", order: 88, writeKana: "じてん", writeAnswer: "辞典", readWord: "辞書", readAnswer: "じしょ", okuriPrompt: "やめる", okuriAnswer: "辞める" },
  { kanji: "失", order: 89, writeKana: "しっぱい", writeAnswer: "失敗", readWord: "失礼", readAnswer: "しつれい", okuriPrompt: "うしなう", okuriAnswer: "失う" },
  { kanji: "借", order: 90, writeKana: "しゃっきん", writeAnswer: "借金", readWord: "借りる", readAnswer: "かりる", okuriPrompt: "かりる", okuriAnswer: "借りる" },
  { kanji: "種", order: 91, writeKana: "たねまき", writeAnswer: "種まき", readWord: "種類", readAnswer: "しゅるい", okuriPrompt: "たね", okuriAnswer: "種" },
  { kanji: "周", order: 92, writeKana: "しゅうい", writeAnswer: "周囲", readWord: "周回", readAnswer: "しゅうかい", okuriPrompt: "まわり", okuriAnswer: "周り" },
  { kanji: "祝", order: 93, writeKana: "しゅくじつ", writeAnswer: "祝日", readWord: "祝う", readAnswer: "いわう", okuriPrompt: "いわう", okuriAnswer: "祝う" },
  { kanji: "順", order: 94, writeKana: "じゅんばん", writeAnswer: "順番", readWord: "手順", readAnswer: "てじゅん" },
  { kanji: "初", order: 95, writeKana: "さいしょ", writeAnswer: "最初", readWord: "初雪", readAnswer: "はつゆき", okuriPrompt: "はじめ", okuriAnswer: "初め" },
  { kanji: "松", order: 96, writeKana: "まつば", writeAnswer: "松葉", readWord: "松林", readAnswer: "まつばやし" },
  { kanji: "笑", order: 97, writeKana: "えがお", writeAnswer: "笑顔", readWord: "笑う", readAnswer: "わらう", okuriPrompt: "わらう", okuriAnswer: "笑う" },
  { kanji: "唱", order: 98, writeKana: "がっしょう", writeAnswer: "合唱", readWord: "提唱", readAnswer: "ていしょう" },
  { kanji: "焼", order: 99, writeKana: "やきもの", writeAnswer: "焼き物", readWord: "燃焼", readAnswer: "ねんしょう", okuriPrompt: "やく", okuriAnswer: "焼く" },
  { kanji: "象", order: 100, writeKana: "げんしょう", writeAnswer: "現象", readWord: "気象", readAnswer: "きしょう" },
  { kanji: "照", order: 101, writeKana: "しょうめい", writeAnswer: "照明", readWord: "照る", readAnswer: "てる", okuriPrompt: "てらす", okuriAnswer: "照らす" },
  { kanji: "賞", order: 102, writeKana: "じゅしょう", writeAnswer: "受賞", readWord: "入賞", readAnswer: "にゅうしょう" },
  { kanji: "臣", order: 103, writeKana: "だいじん", writeAnswer: "大臣", readWord: "家臣", readAnswer: "かしん" },
  { kanji: "信", order: 104, writeKana: "しんごう", writeAnswer: "信号", readWord: "信用", readAnswer: "しんよう" },
  { kanji: "成", order: 105, writeKana: "せいこう", writeAnswer: "成功", readWord: "完成", readAnswer: "かんせい", okuriPrompt: "なる", okuriAnswer: "成る" },
  { kanji: "省", order: 106, writeKana: "はんせい", writeAnswer: "反省", readWord: "省く", readAnswer: "はぶく", okuriPrompt: "はぶく", okuriAnswer: "省く" },
  { kanji: "清", order: 107, writeKana: "せいけつ", writeAnswer: "清潔", readWord: "清水", readAnswer: "しみず", okuriPrompt: "きよい", okuriAnswer: "清い" },
  { kanji: "静", order: 108, writeKana: "しずけさ", writeAnswer: "静けさ", readWord: "静止", readAnswer: "せいし", okuriPrompt: "しずか", okuriAnswer: "静か" },
  { kanji: "席", order: 109, writeKana: "せきがえ", writeAnswer: "席替え", readWord: "欠席", readAnswer: "けっせき" },
  { kanji: "積", order: 110, writeKana: "たいせき", writeAnswer: "体積", readWord: "積もる", readAnswer: "つもる", okuriPrompt: "つむ", okuriAnswer: "積む" },
  { kanji: "折", order: 111, writeKana: "おりがみ", writeAnswer: "折り紙", readWord: "骨折", readAnswer: "こっせつ", okuriPrompt: "おる", okuriAnswer: "折る" },
  { kanji: "節", order: 112, writeKana: "せつやく", writeAnswer: "節約", readWord: "季節", readAnswer: "きせつ" },
  { kanji: "説", order: 113, writeKana: "せつめい", writeAnswer: "説明", readWord: "小説", readAnswer: "しょうせつ", okuriPrompt: "とく", okuriAnswer: "説く" },
  { kanji: "浅", order: 114, writeKana: "あさせ", writeAnswer: "浅瀬", readWord: "浅い", readAnswer: "あさい", okuriPrompt: "あさい", okuriAnswer: "浅い" },
  { kanji: "戦", order: 115, writeKana: "さくせん", writeAnswer: "作戦", readWord: "戦う", readAnswer: "たたかう", okuriPrompt: "たたかう", okuriAnswer: "戦う" },
  { kanji: "選", order: 116, writeKana: "せんしゅ", writeAnswer: "選手", readWord: "選ぶ", readAnswer: "えらぶ", okuriPrompt: "えらぶ", okuriAnswer: "選ぶ" },
  { kanji: "然", order: 117, writeKana: "しぜん", writeAnswer: "自然", readWord: "当然", readAnswer: "とうぜん" },
  { kanji: "争", order: 118, writeKana: "あらそい", writeAnswer: "争い", readWord: "競争", readAnswer: "きょうそう", okuriPrompt: "あらそう", okuriAnswer: "争う" },
  { kanji: "倉", order: 119, writeKana: "そうこ", writeAnswer: "倉庫", readWord: "米倉", readAnswer: "こめぐら" },
  { kanji: "巣", order: 120, writeKana: "すあな", writeAnswer: "巣穴", readWord: "鳥の巣", readAnswer: "とりのす" },
  { kanji: "束", order: 121, writeKana: "やくそく", writeAnswer: "約束", readWord: "花束", readAnswer: "はなたば", okuriPrompt: "たばねる", okuriAnswer: "束ねる" },
  { kanji: "側", order: 122, writeKana: "みぎがわ", writeAnswer: "右側", readWord: "外側", readAnswer: "そとがわ" },
  { kanji: "続", order: 123, writeKana: "つづき", writeAnswer: "続き", readWord: "連続", readAnswer: "れんぞく", okuriPrompt: "つづく", okuriAnswer: "続く" },
  { kanji: "卒", order: 124, writeKana: "そつぎょう", writeAnswer: "卒業", readWord: "卒業式", readAnswer: "そつぎょうしき" },
  { kanji: "孫", order: 125, writeKana: "まごむすめ", writeAnswer: "孫娘", readWord: "初孫", readAnswer: "はつまご" },
  { kanji: "帯", order: 126, writeKana: "ねったい", writeAnswer: "熱帯", readWord: "地帯", readAnswer: "ちたい", okuriPrompt: "おびる", okuriAnswer: "帯びる" },
  { kanji: "隊", order: 127, writeKana: "しょうぼうたい", writeAnswer: "消防隊", readWord: "楽隊", readAnswer: "がくたい" },
  { kanji: "達", order: 128, writeKana: "ともだち", writeAnswer: "友達", readWord: "達人", readAnswer: "たつじん" },
  { kanji: "単", order: 129, writeKana: "たんご", writeAnswer: "単語", readWord: "単元", readAnswer: "たんげん" },
  { kanji: "置", order: 130, writeKana: "いち", writeAnswer: "位置", readWord: "放置", readAnswer: "ほうち", okuriPrompt: "おく", okuriAnswer: "置く" },
  { kanji: "仲", order: 131, writeKana: "なかよし", writeAnswer: "仲良し", readWord: "仲間", readAnswer: "なかま" },
  { kanji: "貯", order: 132, writeKana: "ちょきん", writeAnswer: "貯金", readWord: "貯水", readAnswer: "ちょすい", okuriPrompt: "ためる", okuriAnswer: "貯める" },
  { kanji: "兆", order: 133, writeKana: "きざし", writeAnswer: "兆し", readWord: "前兆", readAnswer: "ぜんちょう", okuriPrompt: "きざす", okuriAnswer: "兆す" },
  { kanji: "腸", order: 134, writeKana: "いちょう", writeAnswer: "胃腸", readWord: "小腸", readAnswer: "しょうちょう" },
  { kanji: "低", order: 135, writeKana: "ていおん", writeAnswer: "低温", readWord: "低い", readAnswer: "ひくい", okuriPrompt: "ひくい", okuriAnswer: "低い" },
  { kanji: "底", order: 136, writeKana: "そこぢから", writeAnswer: "底力", readWord: "海底", readAnswer: "かいてい" },
  { kanji: "停", order: 137, writeKana: "ていしゃ", writeAnswer: "停車", readWord: "停止", readAnswer: "ていし" },
  { kanji: "的", order: 138, writeKana: "もくてき", writeAnswer: "目的", readWord: "的中", readAnswer: "てきちゅう" },
  { kanji: "典", order: 139, writeKana: "じてん", writeAnswer: "辞典", readWord: "古典", readAnswer: "こてん" },
  { kanji: "伝", order: 140, writeKana: "でんごん", writeAnswer: "伝言", readWord: "伝える", readAnswer: "つたえる", okuriPrompt: "つたわる", okuriAnswer: "伝わる" },
  { kanji: "徒", order: 141, writeKana: "せいと", writeAnswer: "生徒", readWord: "徒競走", readAnswer: "ときょうそう" },
  { kanji: "努", order: 142, writeKana: "どりょく", writeAnswer: "努力", readWord: "努める", readAnswer: "つとめる", okuriPrompt: "つとめる", okuriAnswer: "努める" },
  { kanji: "灯", order: 143, writeKana: "とうだい", writeAnswer: "灯台", readWord: "街灯", readAnswer: "がいとう", okuriPrompt: "ともる", okuriAnswer: "灯る" },
  { kanji: "堂", order: 144, writeKana: "しょくどう", writeAnswer: "食堂", readWord: "講堂", readAnswer: "こうどう" },
  { kanji: "働", order: 145, writeKana: "ろうどう", writeAnswer: "労働", readWord: "働く", readAnswer: "はたらく", okuriPrompt: "はたらく", okuriAnswer: "働く" },
  { kanji: "特", order: 146, writeKana: "とくてん", writeAnswer: "特典", readWord: "特別", readAnswer: "とくべつ" },
  { kanji: "得", order: 147, writeKana: "とくい", writeAnswer: "得意", readWord: "得る", readAnswer: "える", okuriPrompt: "える", okuriAnswer: "得る" },
  { kanji: "毒", order: 148, writeKana: "どくぶつ", writeAnswer: "毒物", readWord: "消毒", readAnswer: "しょうどく" },
  { kanji: "熱", order: 149, writeKana: "たいねつ", writeAnswer: "耐熱", readWord: "熱い", readAnswer: "あつい", okuriPrompt: "あつい", okuriAnswer: "熱い" },
  { kanji: "念", order: 150, writeKana: "ねんいり", writeAnswer: "念入り", readWord: "記念", readAnswer: "きねん" },
  { kanji: "敗", order: 151, writeKana: "しっぱい", writeAnswer: "失敗", readWord: "勝敗", readAnswer: "しょうはい", okuriPrompt: "やぶれる", okuriAnswer: "敗れる" },
  { kanji: "梅", order: 152, writeKana: "うめぼし", writeAnswer: "梅干し", readWord: "梅林", readAnswer: "ばいりん" },
  { kanji: "博", order: 153, writeKana: "はくらんかい", writeAnswer: "博覧会", readWord: "博士", readAnswer: "はかせ" },
  { kanji: "飯", order: 154, writeKana: "ごはん", writeAnswer: "ご飯", readWord: "夕飯", readAnswer: "ゆうはん", okuriPrompt: "めし", okuriAnswer: "飯" },
  { kanji: "飛", order: 155, writeKana: "ひこうき", writeAnswer: "飛行機", readWord: "飛ぶ", readAnswer: "とぶ", okuriPrompt: "とばす", okuriAnswer: "飛ばす" },
  { kanji: "費", order: 156, writeKana: "しょうひ", writeAnswer: "消費", readWord: "学費", readAnswer: "がくひ" },
  { kanji: "必", order: 157, writeKana: "ひつよう", writeAnswer: "必要", readWord: "必死", readAnswer: "ひっし" },
  { kanji: "票", order: 158, writeKana: "とうひょう", writeAnswer: "投票", readWord: "伝票", readAnswer: "でんぴょう" },
  { kanji: "標", order: 159, writeKana: "もくひょう", writeAnswer: "目標", readWord: "標本", readAnswer: "ひょうほん" },
  { kanji: "不", order: 160, writeKana: "ふあん", writeAnswer: "不安", readWord: "不足", readAnswer: "ふそく" },
  { kanji: "夫", order: 161, writeKana: "ふうふ", writeAnswer: "夫婦", readWord: "大丈夫", readAnswer: "だいじょうぶ" },
  { kanji: "付", order: 162, writeKana: "うけつけ", writeAnswer: "受付", readWord: "付く", readAnswer: "つく", okuriPrompt: "つける", okuriAnswer: "付ける" },
  { kanji: "府", order: 163, writeKana: "せいふ", writeAnswer: "政府", readWord: "京都府", readAnswer: "きょうとふ" },
  { kanji: "副", order: 164, writeKana: "ふくさよう", writeAnswer: "副作用", readWord: "副部長", readAnswer: "ふくぶちょう" },
  { kanji: "粉", order: 165, writeKana: "こなもの", writeAnswer: "粉物", readWord: "花粉", readAnswer: "かふん", okuriPrompt: "こな", okuriAnswer: "粉" },
  { kanji: "兵", order: 166, writeKana: "へいたい", writeAnswer: "兵隊", readWord: "兵力", readAnswer: "へいりょく" },
  { kanji: "別", order: 167, writeKana: "べつべつ", writeAnswer: "別々", readWord: "特別", readAnswer: "とくべつ", okuriPrompt: "わかれる", okuriAnswer: "別れる" },
  { kanji: "辺", order: 168, writeKana: "あたりいったい", writeAnswer: "辺り一帯", readWord: "周辺", readAnswer: "しゅうへん", okuriPrompt: "あたり", okuriAnswer: "辺り" },
  { kanji: "変", order: 169, writeKana: "へんか", writeAnswer: "変化", readWord: "大変", readAnswer: "たいへん", okuriPrompt: "かわる", okuriAnswer: "変わる" },
  { kanji: "便", order: 170, writeKana: "ゆうびん", writeAnswer: "郵便", readWord: "便利", readAnswer: "べんり" },
  { kanji: "包", order: 171, writeKana: "にもつ", writeAnswer: "荷物", readWord: "包装", readAnswer: "ほうそう", okuriPrompt: "つつむ", okuriAnswer: "包む" },
  { kanji: "法", order: 172, writeKana: "ほうりつ", writeAnswer: "法律", readWord: "文法", readAnswer: "ぶんぽう" },
  { kanji: "望", order: 173, writeKana: "きぼう", writeAnswer: "希望", readWord: "望む", readAnswer: "のぞむ", okuriPrompt: "のぞむ", okuriAnswer: "望む" },
  { kanji: "牧", order: 174, writeKana: "ぼくじょう", writeAnswer: "牧場", readWord: "放牧", readAnswer: "ほうぼく" },
  { kanji: "末", order: 175, writeKana: "げつまつ", writeAnswer: "月末", readWord: "週末", readAnswer: "しゅうまつ" },
  { kanji: "満", order: 176, writeKana: "まんてん", writeAnswer: "満点", readWord: "満月", readAnswer: "まんげつ", okuriPrompt: "みちる", okuriAnswer: "満ちる" },
  { kanji: "未", order: 177, writeKana: "みらい", writeAnswer: "未来", readWord: "未定", readAnswer: "みてい" },
  { kanji: "脈", order: 178, writeKana: "さんみゃく", writeAnswer: "山脈", readWord: "文脈", readAnswer: "ぶんみゃく" },
  { kanji: "民", order: 179, writeKana: "こくみん", writeAnswer: "国民", readWord: "住民", readAnswer: "じゅうみん" },
  { kanji: "無", order: 180, writeKana: "むり", writeAnswer: "無理", readWord: "無料", readAnswer: "むりょう" },
  { kanji: "約", order: 181, writeKana: "よやく", writeAnswer: "予約", readWord: "約束", readAnswer: "やくそく" },
  { kanji: "勇", order: 182, writeKana: "ゆうき", writeAnswer: "勇気", readWord: "勇者", readAnswer: "ゆうしゃ" },
  { kanji: "要", order: 183, writeKana: "ひつよう", writeAnswer: "必要", readWord: "要点", readAnswer: "ようてん", okuriPrompt: "いる", okuriAnswer: "要る" },
  { kanji: "養", order: 184, writeKana: "えいよう", writeAnswer: "栄養", readWord: "養分", readAnswer: "ようぶん", okuriPrompt: "やしなう", okuriAnswer: "養う" },
  { kanji: "浴", order: 185, writeKana: "にっこうよく", writeAnswer: "日光浴", readWord: "入浴", readAnswer: "にゅうよく", okuriPrompt: "あびる", okuriAnswer: "浴びる" },
  { kanji: "利", order: 186, writeKana: "べんり", writeAnswer: "便利", readWord: "利用", readAnswer: "りよう" },
  { kanji: "陸", order: 187, writeKana: "たいりく", writeAnswer: "大陸", readWord: "陸上", readAnswer: "りくじょう" },
  { kanji: "良", order: 188, writeKana: "りょうこう", writeAnswer: "良好", readWord: "改良", readAnswer: "かいりょう", okuriPrompt: "よい", okuriAnswer: "良い" },
  { kanji: "料", order: 189, writeKana: "りょうり", writeAnswer: "料理", readWord: "給料", readAnswer: "きゅうりょう" },
  { kanji: "量", order: 190, writeKana: "ぶつりょう", writeAnswer: "物量", readWord: "重量", readAnswer: "じゅうりょう", okuriPrompt: "はかる", okuriAnswer: "量る" },
  { kanji: "輪", order: 191, writeKana: "しゃりん", writeAnswer: "車輪", readWord: "花輪", readAnswer: "はなわ" },
  { kanji: "類", order: 192, writeKana: "しょるい", writeAnswer: "書類", readWord: "種類", readAnswer: "しゅるい" },
  { kanji: "令", order: 193, writeKana: "めいれい", writeAnswer: "命令", readWord: "法令", readAnswer: "ほうれい" },
  { kanji: "冷", order: 194, writeKana: "れいすい", writeAnswer: "冷水", readWord: "冷える", readAnswer: "ひえる", okuriPrompt: "さます", okuriAnswer: "冷ます" },
  { kanji: "例", order: 195, writeKana: "れいぶん", writeAnswer: "例文", readWord: "例外", readAnswer: "れいがい" },
  { kanji: "歴", order: 196, writeKana: "れきし", writeAnswer: "歴史", readWord: "来歴", readAnswer: "らいれき" },
  { kanji: "連", order: 197, writeKana: "れんらく", writeAnswer: "連絡", readWord: "連休", readAnswer: "れんきゅう", okuriPrompt: "つれる", okuriAnswer: "連れる" },
  { kanji: "老", order: 198, writeKana: "ろうじん", writeAnswer: "老人", readWord: "老後", readAnswer: "ろうご", okuriPrompt: "おいる", okuriAnswer: "老いる" },
  { kanji: "労", order: 199, writeKana: "ろうどう", writeAnswer: "労働", readWord: "苦労", readAnswer: "くろう", okuriPrompt: "いたわる", okuriAnswer: "労る" },
  { kanji: "録", order: 200, writeKana: "ろくおん", writeAnswer: "録音", readWord: "記録", readAnswer: "きろく" }
];

window.WORD_MEANINGS = {
  "案内": "行き方や中のようすを つたえること。",
  "以上": "それより 多いこと。そこから 上。",
  "範囲": "きまった ひろがりや 区切り。",
  "繁栄": "さかえて にぎわうこと。",
  "印刷": "字や絵を 紙に うつして たくさん作ること。",
  "順位": "じゅんばんの くらい。",
  "結果": "さいごに そうなった こと。",
  "貨物": "はこぶ にもつ。",
  "課題": "考えたり したりする べき こと。",
  "改善": "わるいところを よくすること。",
  "機械": "しごとを するための しかけや どうぐ。",
  "被害": "ひがいを うけること。",
  "感覚": "見たり さわったりして わかる はたらき。",
  "完成": "作りおえること。",
  "警察官": "人を まもり、じけんを あつかう しごとの人。",
  "保管": "なくさないように たいせつに しまっておくこと。",
  "関係": "たがいに つながりが あること。",
  "観光": "見たり たずねたりして 土地を たのしむこと。",
  "希望": "こうなってほしいと ねがうこと。",
  "世紀": "100年を ひとまとまりに した いい方。",
  "工芸": "手や道具で 作る うつくしい しなもの。",
  "求人": "はたらく人を さがすこと。",
  "救助": "あぶない人を たすけること。",
  "選挙": "えらんで 代表を きめること。",
  "漁業": "魚や 貝を とる しごと。",
  "共同": "いっしょに 力を あわせて すること。",
  "競争": "くらべて 勝ち負けを きそうこと。",
  "半径": "円の まんなかから ふちまでの 長さ。",
  "模型": "ほんものに にせて 作った もの。",
  "風景": "見える けしき。",
  "欠席": "出る べき ところを 休むこと。",
  "実験": "ためして たしかめること。",
  "固定": "うごかないように しっかり とめること。",
  "成功": "うまく できあがること。",
  "天候": "空の ようす。はれや 雨など。",
  "報告": "わかったことや したことを つたえること。",
  "差額": "二つを くらべた ときの ちがいの 金額。",
  "昨年": "きょ年。",
  "観察": "よく見て へんかや ようすを しらべること。",
  "参考": "考える たすけに すること。",
  "産地": "そのものが 多く とれたり 作られたりする 土地。",
  "残念": "うまく いかず、心のこりな こと。",
  "氏名": "名まえ。",
  "歴史": "むかしからの できごとの ながれ。",
  "司法": "ほうりつにもとづいて さばく はたらき。",
  "試験": "力を ためしたり しらべたりすること。",
  "幼児": "小さい 子ども。",
  "政治": "国や まちを おさめること。",
  "辞典": "ことばや じこうを しらべる 本。",
  "失敗": "うまく できないこと。",
  "借金": "お金や ものを かりること。",
  "種類": "なかまの 分け方。",
  "周囲": "まわり。",
  "合唱": "みんなで 声を あわせて うたうこと。",
  "現象": "見たり 気づいたり できる 出来事や ようす。",
  "受賞": "しょうを もらうこと。",
  "信用": "しんじて まかせること。",
  "反省": "じぶんの よくなかったところを ふりかえること。",
  "清潔": "きれいで よごれていないこと。",
  "体積": "ものの かさ。",
  "説明": "わかるように くわしく つたえること。",
  "自然": "人の手を くわえない そのままの ようす。",
  "争い": "たがいに ぶつかりあうこと。",
  "約束": "きめて まもると ちかうこと。",
  "連続": "とぎれずに つづくこと。",
  "卒業": "学校の 学びを おえて 出ること。",
  "貯金": "お金を ためること。",
  "前兆": "これから 何かが おこる 前ぶれ。",
  "目的": "めざす ところ。",
  "伝言": "ことばを かわりに つたえること。",
  "努力": "一生けんめい はげむこと。",
  "特別": "ふつうと ちがって とくに あつかうこと。",
  "消費": "ものを つかったり へらしたりすること。",
  "投票": "えらぶために 票を 入れること。",
  "目標": "めあて。",
  "便利": "つかいやすくて 役に立つこと。",
  "包装": "つつんで かたちを ととのえること。",
  "法律": "社会の きまり。",
  "牧場": "うしや ひつじなどを そだてる ところ。",
  "未来": "これから 先の 時代。",
  "国民": "その国に くらす 人びと。",
  "無料": "お金が いらないこと。",
  "予約": "前もって たのんで おくこと。",
  "栄養": "からだを そだてる もと。",
  "利用": "役に立つように つかうこと。",
  "大陸": "とても 大きな 陸地。",
  "良好": "ぐあいが よいこと。",
  "料理": "食べものを 作ること。",
  "書類": "書いて まとめた しょるいの なかま。",
  "命令": "こうするように と つよく つげること。",
  "例外": "いつもの きまりと ちがうこと。",
  "連絡": "知らせを とどけあうこと。",
  "労働": "はたらくこと。",
  "記録": "あとで わかるように 書きのこすこと。",
  "名案": "すぐれた 考え。",
  "以内": "その 数や はんいを こえない こと。",
  "食塩": "食べものに つかう しお。",
  "青果": "くだものや やさい。",
  "通貨": "お金として つかう もの。",
  "日課": "まい日 すること。",
  "発芽": "めが 出ること。",
  "紀元": "年を 数える はじまりの 年。",
  "国旗": "国を あらわす はた。",
  "会議": "そうだんの あつまり。",
  "要求": "つよく もとめること。",
  "給食": "学校などで 出る 食事。",
  "機会": "ちょうど よい とき。",
  "教訓": "まなびとる べき おしえ。",
  "完全": "足りないところが ないこと。",
  "改善": "前より よくすること。",
  "健康": "からだや 心の ぐあいが よいこと。",
  "功績": "よい はたらきで のこした 手がら。",
  "野菜": "はたけで 作る たべもの。",
  "最高": "いちばん 高い こと。",
  "名産": "その土地で よく知られた しなもの。",
  "手順": "ものごとを する じゅんばん。",
  "最初": "いちばん はじめ。",
  "受賞": "しょうを うけること。",
  "反省": "じぶんを ふりかえること。",
  "席替え": "すわる 場所を かえること。",
  "節約": "むだを へらして 大事に つかうこと。",
  "自然": "そのままの ありさま。",
  "友達": "なかよく つきあう 人。",
  "必要": "なくては こまること。",
  "希望": "のぞみ。",
  "満点": "ぜんぶ できて もらう 点。",
  "勇気": "こわくても 進もうとする 心。",
  "録音": "音を のこすこと。"
};

window.WORD_EXAMPLES = {
  "愛情": "かぞくの {} を かんじる。",
  "案内": "こうえんの 入口で {} を うける。",
  "以上": "きょうは 三十人 {} が あつまった。",
  "衣服": "旅行の まえに {} を そろえる。",
  "順位": "走った あとの {} を 見る。",
  "範囲": "テストの {} を たしかめる。",
  "囲む": "みんなで つくえを {} 。",
  "胃液": "{} の はたらきで 食べものを しょうかする。",
  "印刷": "しりょうを {} して くばる。",
  "英語": "外国の 人と {} で 話す。",
  "繁栄": "まちの {} を いのる。",
  "栄える": "駅の まわりが {} 。",
  "塩水": "水に しおを 入れて {} を 作る。",
  "一億": "日本の 人口は {} を こえる。",
  "参加": "運動会に {} する。",
  "追加": "足りない せつめいを {} する。",
  "結果": "実験の {} を まとめる。",
  "青果": "店に 新せんな {} が ならぶ。",
  "貨物": "船で {} を はこぶ。",
  "課題": "きょうの {} に 取り組む。",
  "発芽": "たねの {} を 観察する。",
  "改善": "生活の しかたを {} する。",
  "機械": "工場で {} が うごく。",
  "被害": "台風の {} が ひろがる。",
  "商店街": "駅前の {} を 歩く。",
  "各地": "雪の 便りが {} から とどく。",
  "感覚": "手で さわって 形を たしかめる {} を 使う。",
  "完成": "図工の 作品が {} した。",
  "完全": "じゅんびが {} に できた。",
  "警察官": "{} が まちを 見回る。",
  "保管": "だいじな 書類を 金庫で {} する。",
  "関係": "二つの できごとの {} を 調べる。",
  "関心": "環境もんだいに {} を もつ。",
  "観光": "休みに 京都を {} する。",
  "観点": "ちがう {} から 考える。",
  "願い事": "たなばたに {} を 書く。",
  "願う": "みんなの しあわせを {} 。",
  "希望": "将来の {} を 話す。",
  "四季": "日本の {} を 楽しむ。",
  "季節": "{} の うつりかわりを かんじる。",
  "世紀": "二十一 {} に 入った。",
  "紀元": "{} 前の できごとを 学ぶ。",
  "喜び": "勝った {} を みんなで 分け合う。",
  "喜ぶ": "よい 知らせを 聞いて {} 。",
  "国旗": "校庭に {} を かかげる。",
  "食器": "つかった {} を あらう。",
  "楽器": "{} を えんそうする。",
  "飛行機": "{} が 空を 飛ぶ。",
  "機会": "発表する {} を もらう。",
  "会議": "クラスで {} を ひらく。",
  "議長": "{} が 話し合いを まとめる。",
  "求人": "店が {} を 出している。",
  "要求": "安全な せつびを {} する。",
  "泣き声": "あかちゃんの {} が 聞こえる。",
  "泣く": "かなしくて {} 。",
  "救急車": "{} が 病院へ 向かう。",
  "救助": "海で {} 活動が 行われる。",
  "救う": "おぼれた 人を {} 。",
  "給食": "きょうの {} を 楽しみにする。",
  "配給": "しなものを みんなに {} する。",
  "選挙": "代表を 決める {} が 行われる。",
  "挙手": "わかった 人が {} する。",
  "挙げる": "答えたい 人は 手を {} 。",
  "漁業": "海べの まちでは {} が さかんだ。",
  "漁船": "{} が 港に もどる。",
  "協力": "友だちと {} して しあげる。",
  "共通": "二人の {} の しゅみを 見つける。",
  "共同": "地域で {} の 作業を する。",
  "協会": "スポーツ {} に 入る。",
  "競争": "速さを {} する。",
  "競技": "いろいろな {} に ちょうせんする。",
  "競う": "記録を {} 。",
  "極地": "{} の きびしい さむさを 学ぶ。",
  "南極": "{} に すむ 生きものを 調べる。",
  "訓練": "ひなん {} を 行う。",
  "教訓": "失敗から {} を 得る。",
  "軍隊": "{} が 国を まもる。",
  "半径": "円の {} を はかる。",
  "直径": "この 円の {} を 書く。",
  "模型": "建物の {} を 作る。",
  "大型": "{} バスが 通る。",
  "風景": "山の {} を えがく。",
  "光景": "めずらしい {} を 見た。",
  "工芸": "伝とう {} を 学ぶ。",
  "欠席": "かぜで 学校を {} した。",
  "欠点": "じぶんの {} を なおしたい。",
  "結ぶ": "ひもを しっかり {} 。",
  "建物": "古い {} を しらべる。",
  "再建": "こわれた 橋の {} が はじまる。",
  "健康": "{} に 気を つける。",
  "健全": "{} な 心を そだてる。",
  "実験": "理科で {} を する。",
  "体験": "しごと {} に さんかする。",
  "固まり": "どろの {} を くだく。",
  "固める": "足もとを {} 。",
  "固定": "にもつを ロープで {} する。",
  "成功": "作戦が {} した。",
  "功績": "大きな {} を たたえる。",
  "好物": "いもうとの {} は いちごだ。",
  "友好": "二つの 国の {} を 深める。",
  "好む": "しずかな 場所を {} 。",
  "天候": "{} を 見て 予定を 決める。",
  "気候": "その 土地の {} を 調べる。",
  "航空": "{} 会社で はたらく。",
  "航海": "長い {} に 出る。",
  "報告": "しらべた ことを {} する。",
  "広告": "新しい 商品の {} を 見る。",
  "差額": "二つの ねだんの {} を 計算する。",
  "野菜": "畑で とれた {} を 食べる。",
  "菜園": "学校の {} で 水やりを する。",
  "最高": "きょうは {} の できだ。",
  "最初": "{} に 名前を 書く。",
  "昨年": "{} の 行事を ふりかえる。",
  "印刷": "プリントを {} して くばる。",
  "観察": "植物の ようすを {} する。",
  "警察": "{} に そうだんする。",
  "参加": "ちいきの 行事に {} する。",
  "参考": "じしょを {} に する。",
  "産地": "りんごの {} を しらべる。",
  "名産": "その 土地の {} を 買う。",
  "散歩": "犬と いっしょに {} する。",
  "解散": "会が {} する。",
  "残り": "おかしの {} を 分ける。",
  "残念": "しあいに 負けて {} だ。",
  "力士": "{} が 土俵で たたかう。",
  "兵士": "{} が 国を まもる。",
  "氏名": "用紙に {} を 書く。",
  "歴史": "まちの {} を 学ぶ。",
  "司法": "{} の しくみを しらべる。",
  "試験": "あした {} が ある。",
  "試合": "大事な {} に のぞむ。",
  "幼児": "{} が 公園で あそぶ。",
  "政治": "{} の しごとを 学ぶ。",
  "辞典": "ことばを {} で しらべる。",
  "失敗": "{} を 次に いかす。",
  "失礼": "へんじが おそくなり {} しました。",
  "借金": "{} を へらす 努力を する。",
  "借りる": "図書館で 本を {} 。",
  "種類": "花の {} を 数える。",
  "周囲": "{} の 安全を たしかめる。",
  "祝日": "{} は 学校が 休みだ。",
  "祝う": "たん生日を {} 。",
  "順番": "{} を まもって ならぶ。",
  "最初": "{} に あいさつを する。",
  "笑顔": "{} で むかえる。",
  "笑う": "おもしろくて {} 。",
  "合唱": "みんなで {} を する。",
  "焼く": "パンを {} 。",
  "現象": "ふしぎな {} を しらべる。",
  "照明": "{} を つける。",
  "照る": "朝から 太陽が {} 。",
  "受賞": "作文が 入しょうして {} した。",
  "信号": "{} を 守って わたる。",
  "信用": "約束を 守って {} を 得る。",
  "反省": "一日の こうどうを {} する。",
  "清潔": "{} な 教室を たもつ。",
  "静けさ": "夜の {} を かんじる。",
  "静か": "図書室では {} に する。",
  "席替え": "{} で となりが かわる。",
  "体積": "はこの {} を もとめる。",
  "折り紙": "{} で つるを 折る。",
  "節約": "水を 大切に して {} する。",
  "説明": "使い方を {} する。",
  "小説": "{} を 一さつ 読む。",
  "浅い": "川が {} ところを わたる。",
  "作戦": "しあいの {} を 立てる。",
  "戦う": "あきらめずに {} 。",
  "選手": "{} を おうえんする。",
  "選ぶ": "すきな 本を {} 。",
  "自然": "{} を たいせつに する。",
  "争い": "{} を さける。",
  "倉庫": "{} に にもつを 入れる。",
  "花束": "そつぎょうしきで {} を わたす。",
  "右側": "ろうかの {} を 歩く。",
  "続き": "本の {} を 読む。",
  "続く": "雨の日が {} 。",
  "卒業": "{} を いわう。",
  "孫娘": "{} が あそびに 来る。",
  "熱帯": "{} の しょくぶつを 学ぶ。",
  "消防隊": "{} が 火事の 現場へ 向かう。",
  "友達": "{} と 公園で あそぶ。",
  "位置": "地図で 学校の {} を たしかめる。",
  "仲間": "{} と 力を あわせる。",
  "貯金": "こづかいを {} する。",
  "前兆": "雨の {} が 見える。",
  "胃腸": "{} の ちょう子を ととのえる。",
  "低温": "{} で ほぞんする。",
  "底力": "さいごに {} を 見せる。",
  "停車": "バスが バスていに {} する。",
  "目的": "見学の {} を はっきり させる。",
  "古典": "{} を 音読する。",
  "伝言": "{} を 家族に つたえる。",
  "伝える": "大事な 話を きちんと {} 。",
  "生徒": "{} が 教室に 入る。",
  "努力": "{} を つづける。",
  "努める": "さいごまで やりぬくように {} 。",
  "灯台": "{} の 光が 海を てらす。",
  "食堂": "学校の {} で 昼ご飯を 食べる。",
  "働く": "町の 人が いろいろな しごとで {} 。",
  "特別": "きょうは {} な 日だ。",
  "得意": "{} な 教科を のばす。",
  "得る": "よい けいけんを {} 。",
  "毒物": "{} を あんぜんに あつかう。",
  "消毒": "手を きれいに {} する。",
  "耐熱": "{} の さらを つかう。",
  "念入り": "{} に しらべる。",
  "記念": "旅行の {} に 写真を とる。",
  "勝敗": "しあいの {} が 決まる。",
  "博覧会": "{} で 新しい ぎじゅつを 見る。",
  "飛ぶ": "鳥が 空を {} 。",
  "飛ばす": "紙ひこうきを {} 。",
  "消費": "電気を むだに {} しない。",
  "必要": "じゅんびに {} な ものを そろえる。",
  "投票": "学級だいひょうに {} する。",
  "目標": "{} を 立てて 練習する。",
  "不安": "{} な 気もちを 先生に 話す。",
  "便利": "{} な どうぐを つかう。",
  "受付": "会場の {} を すませる。",
  "政府": "{} の しごとを 学ぶ。",
  "副作用": "くすりの {} を たしかめる。",
  "花粉": "{} が 多い 日は マスクを する。",
  "法律": "{} を 守って くらす。",
  "希望": "しょうらいの {} を 書く。",
  "牧場": "{} で 牛を 見る。",
  "月末": "{} に しはらいを する。",
  "満点": "テストで {} を とる。",
  "未来": "{} の くらしを そうぞうする。",
  "山脈": "長い {} が つづく。",
  "国民": "{} の くらしを ささえる。",
  "無料": "{} で 見学できる。",
  "予約": "図書室の 本を {} する。",
  "勇気": "{} を 出して 手を あげる。",
  "栄養": "{} の ある 食事を とる。",
  "養う": "生きる 力を {} 。",
  "日光浴": "天気の よい日に {} を する。",
  "利用": "図書館を {} する。",
  "大陸": "世界の {} を 地図で 見る。",
  "良好": "けんこう じょうたいは {} だ。",
  "料理": "{} を 手つだう。",
  "物量": "{} の ちがいが しょうぶを 分ける。",
  "車輪": "自転車の {} を しらべる。",
  "書類": "{} を まとめて 出す。",
  "命令": "{} に したがって うごく。",
  "冷水": "{} で 手を あらう。",
  "例文": "{} を まねして 文を 作る。",
  "例外": "{} を みとめる。",
  "連絡": "{} を わすれずに する。",
  "連休": "{} に 家族で 出かける。",
  "老人": "{} を いたわる。",
  "老後": "{} の くらしを 考える。",
  "労働": "{} の たいせつさを 学ぶ。",
  "録音": "音楽を {} する。"
};

Object.assign(window.WORD_EXAMPLES, {
  "愛鳥": "{} を 大切に そだてる。",
  "雨衣": "雨の日は {} を きる。",
  "第一位": "かけっこで {} に なる。",
  "目印": "赤い 旗を {} に する。",
  "英雄": "国を すくった {} の 話を 読む。",
  "億万": "{} の ほしが 空に かがやく。",
  "新芽": "木の えだに {} が 出る。",
  "改まる": "あいさつの 場で ことばづかいが {} 。",
  "改める": "よくない くせを {} 。",
  "器械": "体そうで 使う {} を ならべる。",
  "公害": "{} から まちを 守る。",
  "街角": "{} の 花だんに 水を やる。",
  "各自": "{} で じゅんびを する。",
  "目覚める": "朝 早く {} 。",
  "覚える": "あたらしい 漢字を {} 。",
  "官公署": "{} に 書類を 出す。",
  "水道管": "地下に {} が 通っている。",
  "関": "むかしの {} あとを 見学する。",
  "願書": "学校に {} を 出す。",
  "希少": "{} な 動物を 大切に まもる。",
  "喜劇": "みんなで {} を 見て わらう。",
  "旗印": "チームの {} を かかげる。",
  "求める": "より よい 答えを {} 。",
  "共に": "友だちと {} 学ぶ。",
  "手鏡": "{} で かおを うつす。",
  "眼鏡": "{} を かけて 本を 読む。",
  "極める": "わざを {} ために れんしゅうする。",
  "海軍": "むかしの {} の しごとを 調べる。",
  "郡部": "{} の くらしを 調べる。",
  "郡山": "{} 市の 位置を 地図で 見る。",
  "芸名": "その かしゅの {} を 覚える。",
  "欠ける": "月が すこし {} 。",
  "建てる": "新しい 家を {} 。",
  "小康": "体の ぐあいが {} を たもつ。",
  "時差": "国どうしの {} を 調べる。",
  "差す": "日ざしが まどから {} 。",
  "機材": "えいぞうの {} を はこぶ。",
  "木材": "{} を つかって 棚を 作る。",
  "昨夜": "{} は 雨が ふった。",
  "札束": "えい画で {} を 見た。",
  "名札": "{} を むねに つける。",
  "刷る": "年がじょうを {} 。",
  "必殺": "{} わざで 勝負を 決める。",
  "相殺": "二つの 力が {} される。",
  "殺す": "虫を {} くすりに 気を つける。",
  "参る": "つかれて {} 。",
  "産む": "親鳥が たまごを {} 。",
  "散る": "さくらの 花が {} 。",
  "残す": "大事な 記録を {} 。",
  "山田氏": "{} が 会で あいさつする。",
  "史上": "{} はじめての 記録が 出た。",
  "上司": "しごとの ことを {} に そうだんする。",
  "試す": "あたらしい ほうほうを {} 。",
  "児童": "{} が 校庭で あそぶ。",
  "治る": "けがが すっかり {} 。",
  "治す": "こわれた ところを {} 。",
  "辞書": "{} で ことばを しらべる。",
  "辞める": "長く つづけた 役を {} 。",
  "失う": "たいせつな ものを {} 。",
  "種まき": "春に {} を する。",
  "種": "ひまわりの {} を まく。",
  "周回": "うんどうじょうを {} する。",
  "周り": "いけの {} を 歩く。",
  "初雪": "{} が 校庭に つもる。",
  "初め": "文の {} を ていねいに 書く。",
  "松葉": "{} が 地面に 落ちる。",
  "松林": "{} を ぬけて 海へ 行く。",
  "提唱": "新しい かつどうを {} する。",
  "焼き物": "店に きれいな {} が ならぶ。",
  "燃焼": "ものが {} すると 熱が 出る。",
  "気象": "{} の へんかを 調べる。",
  "照らす": "月の 光が みちを {} 。",
  "入賞": "作品が {} して うれしい。",
  "大臣": "{} が 記者に 話す。",
  "家臣": "むかしの {} の くらしを 学ぶ。",
  "成る": "ねがいが かなって 本当に {} 。",
  "省く": "むだを {} くふうを する。",
  "清水": "{} が 山から わき出る。",
  "清い": "{} 水が ながれる。",
  "静止": "しんごうで 車が {} する。",
  "積もる": "雪が 校庭に {} 。",
  "積む": "トラックに にもつを {} 。",
  "骨折": "ころんで 足を {} した。",
  "折る": "色紙を 半分に {} 。",
  "説く": "先生が 平和の 大切さを {} 。",
  "浅瀬": "{} で 小魚を 見つける。",
  "当然": "やくそくを 守るのは {} だ。",
  "争う": "小さな ことで {} のは よくない。",
  "米倉": "{} に こめを しまう。",
  "巣穴": "きつねが {} から 出てきた。",
  "鳥の巣": "木の 上に {} が ある。",
  "束ねる": "紙を ひもで {} 。",
  "外側": "はこの {} を ぬる。",
  "卒業式": "{} で 歌を うたう。",
  "初孫": "{} が 生まれて 家族が よろこぶ。",
  "地帯": "この あたりは 雪の 多い {} だ。",
  "帯びる": "空が 赤みを {} 。",
  "楽隊": "{} の えんそうが ひびく。",
  "達人": "その 人は こま回しの {} だ。",
  "単語": "あたらしい {} を 覚える。",
  "単元": "この {} の まとめを する。",
  "放置": "ごみを {} しては いけない。",
  "置く": "つくえの 上に 本を {} 。",
  "仲良し": "{} の 友だちと かえる。",
  "貯水": "{} タンクに 水を ためる。",
  "貯める": "こづかいを 少しずつ {} 。",
  "兆し": "春の {} が 見える。",
  "兆す": "空が 雨を {} 。",
  "小腸": "{} では えいようを すいしゅうする。",
  "低い": "この 山は 高さが {} 。",
  "海底": "{} に ねむる しげんを 調べる。",
  "停止": "エレベーターが とちゅうで {} した。",
  "的中": "よそうが {} して うれしい。",
  "伝わる": "大事な 話が みんなに {} 。",
  "徒競走": "うんどう会の {} に 出る。",
  "街灯": "夜道を {} が てらす。"
});
