module.exports = {
  grade: 3,
  entries: {
    事: { write: { written: "しごと", pronounced: "しごと", category: "せいかつ", example: "おうちの {} を てつだう。" } },
    発: { write: { written: "はっぴょう", pronounced: "はっぴょう", category: "がっこう", example: "みんなの まえで {} を する。" } },
    対: { write: { written: "たいせん", pronounced: "たいせん", category: "あそび", example: "つぎの しあいで {} する。" } },
    部: { write: { written: "ぶぶん", pronounced: "ぶぶん", category: "べんきょう", example: "むずかしい {} を なおす。" } },
    者: { write: { written: "いしゃ", pronounced: "いしゃ", category: "ひと", example: "びょうきの ときは {} に みてもらう。" } },
    業: { write: { written: "じゅぎょう", pronounced: "じゅぎょう", category: "がっこう", example: "さんすうの {} が はじまる。" } },
    相: { write: { written: "そうだん", pronounced: "そうだん", category: "かいわ", example: "こまった ことを せんせいに {} する。" } },
    定: { write: { written: "よてい", pronounced: "よてい", category: "せいかつ", example: "あしたの {} を きめる。" } },
    員: { write: { written: "いいん", pronounced: "いいん", category: "がっこう", example: "クラスの {} を えらぶ。" } },
    開: { write: { written: "かいかいしき", pronounced: "かいかいしき", category: "ぎょうじ", example: "うんどうかいの {} が はじまる。" } },
    問: { write: { written: "もんだい", pronounced: "もんだい", category: "べんきょう", example: "この {} を といてみよう。" } },
    代: { write: { written: "だいきん", pronounced: "だいきん", category: "せいかつ", example: "かいものの {} を はらう。" } },
    実: { write: { written: "じつりょく", pronounced: "じつりょく", category: "せいちょう", example: "れんしゅうして {} を のばす。" } },
    決: { write: { written: "けってい", pronounced: "けってい", category: "かつどう", example: "みんなで ルールを {} する。" } },
    動: { write: { written: "うんどう", pronounced: "うんどう", category: "からだ", example: "こうていで {} する。" } },
    全: { write: { written: "あんぜん", pronounced: "あんぜん", category: "せいかつ", example: "{} に きを つけて あるく。" } },
    表: { write: { written: "はっぴょう", pronounced: "はっぴょう", category: "がっこう", example: "しらべた ことを {} する。" } },
    調: { write: { written: "ちょうさ", pronounced: "ちょうさ", category: "べんきょう", example: "まちの ようすを {} する。" } },
    化: { write: { written: "へんか", pronounced: "へんか", category: "りか", example: "しょくぶつの {} を かんさつする。" } },
    主: { write: { written: "しゅじんこう", pronounced: "しゅじんこう", category: "こくご", example: "ものがたりの {} を たしかめる。" } },
    題: { write: { written: "だいめい", pronounced: "だいめい", category: "こくご", example: "ほんの {} を よむ。" } },
    意: { write: { written: "いけん", pronounced: "いけん", category: "かいわ", example: "じぶんの {} を いう。" } },
    度: { write: { written: "おんど", pronounced: "おんど", category: "りか", example: "みずの {} を はかる。" } },
    期: { write: { written: "がっき", pronounced: "がっき", category: "がっこう", example: "二{} が はじまる。" } },
    持: { write: { written: "もちもの", pronounced: "もちもの", category: "がっこう", example: "あしたの {} を そろえる。" } },
    取: { write: { written: "とる", pronounced: "とる", category: "せいかつ", example: "しゃしんを {}。" } },
    都: { write: { written: "みやこ", pronounced: "みやこ", category: "しゃかい", example: "むかしの {} の ようすを 学ぶ。" } },
    和: { write: { written: "へいわ", pronounced: "へいわ", category: "こころ", example: "{} を たいせつに したい。" } },
    平: { write: { written: "へいきん", pronounced: "へいきん", category: "さんすう", example: "三つの かずの {} を だす。" } },
    世: { write: { written: "せかい", pronounced: "せかい", category: "しゃかい", example: "{} の くにを ちずで みる。" } },
    受: { write: { written: "うけつけ", pronounced: "うけつけ", category: "ぎょうじ", example: "かいじょうで {} を すませる。" } },
    区: { write: { written: "くいき", pronounced: "くいき", category: "しゃかい", example: "この {} を せんで くぎる。" } },
    県: { write: { written: "けん", pronounced: "けん", category: "しゃかい", example: "すんでいる {} を ちずで みる。" } },
    進: { write: { written: "しんこう", pronounced: "しんこう", category: "かつどう", example: "かいを じゅんちょうに {} させる。" } },
    安: { write: { written: "あんしん", pronounced: "あんしん", category: "こころ", example: "{} して ねむる。" } },
    院: { write: { written: "びょういん", pronounced: "びょういん", category: "せいかつ", example: "けがをしたので {} へ いく。" } },
    指: { write: { written: "ゆびさき", pronounced: "ゆびさき", category: "からだ", example: "{} で ちいさな ものを つまむ。" } },
    界: { write: { written: "せかい", pronounced: "せかい", category: "しゃかい", example: "{} の くにぐにを 学ぶ。" } },
    第: { write: { written: "だいいち", pronounced: "だいいち", category: "じゅんばん", example: "{} コースを はしる。" } },
    予: { write: { written: "よしゅう", pronounced: "よしゅう", category: "べんきょう", example: "あしたの ないようを {} する。" } },
    向: { write: { written: "ほうこう", pronounced: "ほうこう", category: "せいかつ", example: "すすむ {} を たしかめる。" } },
    勝: { write: { written: "しょうぶ", pronounced: "しょうぶ", category: "スポーツ", example: "{} に かつ。" } },
    面: { write: { written: "がめん", pronounced: "がめん", category: "もの", example: "タブレットの {} を みる。" } },
    委: { write: { written: "いいん", pronounced: "いいん", category: "がっこう", example: "そうじ {} の しごとを する。" } },
    反: { write: { written: "はんたい", pronounced: "はんたい", category: "かいわ", example: "{} の いけんも きいてみる。" } },
    重: { write: { written: "たいじゅう", pronounced: "たいじゅう", category: "からだ", example: "{} を はかる。" } },
    集: { write: { written: "しゅうごう", pronounced: "しゅうごう", category: "ぎょうじ", example: "こうていに {} する。" } },
    物: { write: { written: "にもつ", pronounced: "にもつ", category: "せいかつ", example: "{} を もって いく。" } },
    使: { write: { written: "つかいかた", pronounced: "つかいかた", category: "せいかつ", example: "どうぐの {} を おぼえる。" } },
    所: { write: { written: "ばしょ", pronounced: "ばしょ", category: "せいかつ", example: "{} を きめて まつ。" } },
    次: { write: { written: "つぎ", pronounced: "つぎ", category: "じゅんばん", example: "{} の ひとが はいる。" } },
    品: { write: { written: "しなもの", pronounced: "しなもの", category: "せいかつ", example: "ほしい {} を えらぶ。" } },
    死: { write: { written: "し", pronounced: "し", category: "いのち", example: "いきものの {} について 学ぶ。" } },
    係: { write: { written: "かかり", pronounced: "かかり", category: "がっこう", example: "きょうの {} の しごとを する。" } },
    感: { write: { written: "かんそう", pronounced: "かんそう", category: "こくご", example: "ほんを よんだ {} を かく。" } },
    投: { write: { written: "とうきゅう", pronounced: "とうきゅう", category: "スポーツ", example: "ボールを つよく {} する。" } },
    打: { write: { written: "だきゅう", pronounced: "だきゅう", category: "スポーツ", example: "バットで {} する。" } },
    始: { write: { written: "はじめ", pronounced: "はじめ", category: "じゅんばん", example: "{} に あいさつを する。" } },
    島: { write: { written: "しまぐに", pronounced: "しまぐに", category: "しゃかい", example: "{} の くらしを しらべる。" } },
    両: { write: { written: "りょうほう", pronounced: "りょうほう", category: "さんすう", example: "{} の いけんを きく。" } },
    式: { write: { written: "しき", pronounced: "しき", category: "ぎょうじ", example: "そつぎょう{} で うたう。" } },
    運: { write: { written: "うんてん", pronounced: "うんてん", category: "のりもの", example: "あんぜんに {} する。" } },
    終: { write: { written: "おわり", pronounced: "おわり", category: "じゅんばん", example: "{} まで がんばる。" } },
    住: { write: { written: "じゅうしょ", pronounced: "じゅうしょ", category: "せいかつ", example: "{} を かく。" } },
    談: { write: { written: "そうだん", pronounced: "そうだん", category: "かいわ", example: "なやみを {} する。" } },
    真: { write: { written: "しゃしん", pronounced: "しゃしん", category: "もの", example: "{} を とる。" } },
    流: { write: { written: "ながれ", pronounced: "ながれ", category: "りか", example: "かわの {} を 見る。" } },
    有: { write: { written: "ゆうめい", pronounced: "ゆうめい", category: "しゃかい", example: "{} な ばしょへ いく。" } },
    局: { write: { written: "ゆうびんきょく", pronounced: "ゆうびんきょく", category: "まち", example: "{} で はがきを 出す。" } },
    放: { write: { written: "ほうそう", pronounced: "ほうそう", category: "テレビ", example: "よるの {} を みる。" } },
    球: { write: { written: "やきゅう", pronounced: "やきゅう", category: "スポーツ", example: "{} を する。" } },
    急: { write: { written: "きゅうこう", pronounced: "きゅうこう", category: "のりもの", example: "{} れっしゃが とまる。" } },
    送: { write: { written: "みおくり", pronounced: "みおくり", category: "せいかつ", example: "えきまで {} に いく。" } },
    役: { write: { written: "やくわり", pronounced: "やくわり", category: "かつどう", example: "それぞれの {} を はたす。" } },
    身: { write: { written: "みのまわり", pronounced: "みのまわり", category: "せいかつ", example: "{} を きれいに する。" } },
    由: { write: { written: "じゆう", pronounced: "じゆう", category: "こころ", example: "{} に えらぶ。" } },
    転: { write: { written: "うんてん", pronounced: "うんてん", category: "のりもの", example: "じてんしゃを あんぜんに {} する。" } },
    研: { write: { written: "けんきゅう", pronounced: "けんきゅう", category: "りか", example: "しょくぶつの そだちかたを {} する。" } },
    消: { write: { written: "しょうぼう", pronounced: "しょうぼう", category: "まち", example: "{} くんれんに さんかする。" } },
    神: { write: { written: "じんじゃ", pronounced: "じんじゃ", category: "まち", example: "{} に おまいりする。" } },
    配: { write: { written: "くばりかた", pronounced: "くばりかた", category: "かつどう", example: "しりょうの {} を きめる。" } },
    宮: { write: { written: "みや", pronounced: "みや", category: "しゃかい", example: "むかしの {} の くらしを 学ぶ。" } },
    究: { write: { written: "けんきゅう", pronounced: "けんきゅう", category: "りか", example: "{} を つづける。" } },
    育: { write: { written: "そだてかた", pronounced: "そだてかた", category: "せいかつ", example: "はなの {} を しらべる。" } },
    起: { write: { written: "おきる", pronounced: "おきる", category: "せいかつ", example: "あさ はやく {}。" } },
    着: { write: { written: "きがえ", pronounced: "きがえ", category: "せいかつ", example: "あさの {} を すませる。" } },
    乗: { write: { written: "じょうしゃ", pronounced: "じょうしゃ", category: "のりもの", example: "でんしゃに {} する。" } },
    想: { write: { written: "そうぞう", pronounced: "そうぞう", category: "こころ", example: "しょうらいを {} する。" } },
    病: { write: { written: "びょうき", pronounced: "びょうき", category: "せいかつ", example: "{} に ならないように きをつける。" } },
    農: { write: { written: "のうか", pronounced: "のうか", category: "しごと", example: "{} の しごとを 学ぶ。" } },
    州: { write: { written: "しゅう", pronounced: "しゅう", category: "しゃかい", example: "アメリカの {} を ちずで 見る。" } },
    待: { write: { written: "まちあわせ", pronounced: "まちあわせ", category: "せいかつ", example: "{} の じかんを きめる。" } },
    族: { write: { written: "かぞく", pronounced: "かぞく", category: "ひと", example: "{} で りょこうする。" } },
    銀: { write: { written: "ぎんいろ", pronounced: "ぎんいろ", category: "もの", example: "{} の かみを おる。" } },
    助: { write: { written: "たすけ", pronounced: "たすけ", category: "こころ", example: "こまった ときの {} に なる。" } },
    追: { write: { written: "ついせき", pronounced: "ついせき", category: "ちょうさ", example: "あしあとを {} する。" } },
    商: { write: { written: "しょうてん", pronounced: "しょうてん", category: "まち", example: "{} が ならぶ みちを あるく。" } },
    葉: { write: { written: "おちば", pronounced: "おちば", category: "しぜん", example: "{} を ひろう。" } },
    落: { write: { written: "おちる", pronounced: "おちる", category: "しぜん", example: "きから はが {}。" } },
    医: { write: { written: "いりょう", pronounced: "いりょう", category: "せいかつ", example: "{} の しごとを 学ぶ。" } },
    仕: { write: { written: "しごと", pronounced: "しごと", category: "せいかつ", example: "まいにちの {} を がんばる。" } },
    去: { write: { written: "きょねん", pronounced: "きょねん", category: "じかん", example: "{} の おもいでを はなす。" } },
    味: { write: { written: "あじみ", pronounced: "あじみ", category: "たべもの", example: "スープを {} する。" } },
    負: { write: { written: "まけ", pronounced: "まけ", category: "スポーツ", example: "きょうの しあいは {} だった。" } },
    写: { write: { written: "しゃしん", pronounced: "しゃしん", category: "もの", example: "{} を とる。" } },
    守: { write: { written: "やくそく", pronounced: "やくそく", category: "せいかつ", example: "{} を まもる。" } },
    美: { write: { written: "びじゅつ", pronounced: "びじゅつ", category: "がっこう", example: "{} の じかんに えを かく。" } },
    命: { write: { written: "いのち", pronounced: "いのち", category: "いのち", example: "{} を たいせつに する。" } },
    福: { write: { written: "こうふく", pronounced: "こうふく", category: "こころ", example: "{} を ねがう。" } },
    整: { write: { written: "せいり", pronounced: "せいり", category: "せいかつ", example: "つくえの うえを {} する。" } },
    横: { write: { written: "おうだんほどう", pronounced: "おうだんほどう", category: "まち", example: "{} を わたる。" } },
    深: { write: { written: "ふかさ", pronounced: "ふかさ", category: "さんすう", example: "みずの {} を はかる。" } },
    申: { write: { written: "もうしこみ", pronounced: "もうしこみ", category: "ぎょうじ", example: "{} を する。" } },
    様: { write: { written: "ようす", pronounced: "ようす", category: "かんさつ", example: "はなの {} を 見る。" } },
    港: { write: { written: "みなと", pronounced: "みなと", category: "しゃかい", example: "{} に ふねが とまる。" } },
    注: { write: { written: "ちゅうい", pronounced: "ちゅうい", category: "せいかつ", example: "{} して あるく。" } },
    階: { write: { written: "かいだん", pronounced: "かいだん", category: "せいかつ", example: "{} を のぼる。" } },
    路: { write: { written: "どうろ", pronounced: "どうろ", category: "まち", example: "{} を わたる ときは みぎひだりを 見る。" } },
    悪: { write: { written: "あくろ", pronounced: "あくろ", category: "みち", example: "あめの あとの {} に きをつける。" } },
    他: { write: { written: "ほか", pronounced: "ほか", category: "かいわ", example: "{} の 人にも きいてみる。" } },
    橋: { write: { written: "はし", pronounced: "はし", category: "まち", example: "大きな {} を わたる。" } },
    岸: { write: { written: "かわぎし", pronounced: "かわぎし", category: "しぜん", example: "{} を あるく。" } },
    客: { write: { written: "おきゃくさん", pronounced: "おきゃくさん", category: "ひと", example: "{} が みせに 来る。" } },
    登: { write: { written: "とうこう", pronounced: "とうこう", category: "がっこう", example: "あさ はやめに {} する。" } },
    速: { write: { written: "そくど", pronounced: "そくど", category: "さんすう", example: "くるまの {} を はかる。" } },
    央: { write: { written: "ちゅうおう", pronounced: "ちゅうおう", category: "さんすう", example: "ちずの {} に しるしを つける。" } },
    号: { write: { written: "ごうれい", pronounced: "ごうれい", category: "かつどう", example: "{} で うごく。" } },
    館: { write: { written: "としょかん", pronounced: "としょかん", category: "まち", example: "{} で 本を かりる。" } },
    屋: { write: { written: "ほんや", pronounced: "ほんや", category: "まち", example: "{} で 本を さがす。" } },
    根: { write: { written: "ねっこ", pronounced: "ねっこ", category: "しぜん", example: "木の {} を 見る。" } },
    苦: { write: { written: "くろう", pronounced: "くろう", category: "こころ", example: "{} して おぼえた。" } },
    具: { write: { written: "どうぐ", pronounced: "どうぐ", category: "もの", example: "べんりな {} を つかう。" } },
    鉄: { write: { written: "てつぼう", pronounced: "てつぼう", category: "うんどう", example: "{} の れんしゅうを する。" } },
    返: { write: { written: "へんじ", pronounced: "へんじ", category: "かいわ", example: "{} を わすれない。" } },
    短: { write: { written: "みじかさ", pronounced: "みじかさ", category: "さんすう", example: "ひもの {} を はかる。" } },
    油: { write: { written: "あぶら", pronounced: "あぶら", category: "たべもの", example: "{} を つかって いためる。" } },
    昭: { write: { written: "しょうわ", pronounced: "しょうわ", category: "しゃかい", example: "{} の くらしを 学ぶ。" } },
    植: { write: { written: "うえき", pronounced: "うえき", category: "しぜん", example: "{} に みずを やる。" } },
    宿: { write: { written: "しゅくだい", pronounced: "しゅくだい", category: "べんきょう", example: "{} を わすれずに する。" } },
    薬: { write: { written: "くすり", pronounced: "くすり", category: "せいかつ", example: "{} を のむ。" } },
    習: { write: { written: "ならいごと", pronounced: "ならいごと", category: "せいかつ", example: "{} に 行く。" } },
    倍: { write: { written: "ばい", pronounced: "ばい", category: "さんすう", example: "三の 二{} は 六。" } },
    駅: { write: { written: "えきまえ", pronounced: "えきまえ", category: "まち", example: "{} で まちあわせする。" } },
    波: { write: { written: "なみおと", pronounced: "なみおと", category: "しぜん", example: "{} を きく。" } },
    洋: { write: { written: "たいへいよう", pronounced: "たいへいよう", category: "しゃかい", example: "{} の ひろさを 学ぶ。" } },
    旅: { write: { written: "たび", pronounced: "たび", category: "せいかつ", example: "{} の じゅんびを する。" } },
    級: { write: { written: "がっきゅう", pronounced: "がっきゅう", category: "がっこう", example: "{} の みんなで はなしあう。" } },
    幸: { write: { written: "しあわせ", pronounced: "しあわせ", category: "こころ", example: "{} な きもちに なる。" } },
    練: { write: { written: "れんしゅう", pronounced: "れんしゅう", category: "がっこう", example: "{} を つづける。" } },
    軽: { write: { written: "かるさ", pronounced: "かるさ", category: "さんすう", example: "にもつの {} を くらべる。" } },
    等: { write: { written: "とうばん", pronounced: "とうばん", category: "がっこう", example: "{} の しごとを する。" } },
    曲: { write: { written: "がっきょく", pronounced: "がっきょく", category: "おんがく", example: "{} を きく。" } },
    庭: { write: { written: "にわ", pronounced: "にわ", category: "せいかつ", example: "{} で あそぶ。" } },
    血: { write: { written: "けつえき", pronounced: "けつえき", category: "りか", example: "{} の はたらきを 学ぶ。" } },
    温: { write: { written: "おんど", pronounced: "おんど", category: "りか", example: "みずの {} を はかる。" } },
    庫: { write: { written: "そうこ", pronounced: "そうこ", category: "まち", example: "{} から にもつを 出す。" } },
    坂: { write: { written: "さかみち", pronounced: "さかみち", category: "まち", example: "{} を のぼる。" } },
    服: { write: { written: "ようふく", pronounced: "ようふく", category: "せいかつ", example: "{} を たたむ。" } },
    息: { write: { written: "いき", pronounced: "いき", category: "からだ", example: "大きく {} を すう。" } },
    板: { write: { written: "こくばん", pronounced: "こくばん", category: "がっこう", example: "{} に もじを かく。" } },
    列: { write: { written: "れつ", pronounced: "れつ", category: "じゅんばん", example: "{} に ならぶ。" } },
    遊: { write: { written: "ゆうえんち", pronounced: "ゆうえんち", category: "せいかつ", example: "{} へ 行く。" } },
    君: { write: { written: "きみ", pronounced: "きみ", category: "かいわ", example: "{} は どう 思う。" } },
    飲: { write: { written: "のみもの", pronounced: "のみもの", category: "たべもの", example: "{} を じゅんびする。" } },
    章: { write: { written: "ぶんしょう", pronounced: "ぶんしょう", category: "こくご", example: "{} を ていねいに よむ。" } },
    酒: { write: { written: "あまざけ", pronounced: "あまざけ", category: "たべもの", example: "あたたかい {} を のむ。" } },
    悲: { write: { written: "かなしみ", pronounced: "かなしみ", category: "こころ", example: "{} を かんじる。" } },
    秒: { write: { written: "びょう", pronounced: "びょう", category: "さんすう", example: "十{} は どれくらいか かぞえる。" } },
    暗: { write: { written: "くらやみ", pronounced: "くらやみ", category: "しぜん", example: "{} の なかを あるく。" } },
    勉: { write: { written: "べんきょう", pronounced: "べんきょう", category: "がっこう", example: "{} を がんばる。" } },
    陽: { write: { written: "たいよう", pronounced: "たいよう", category: "しぜん", example: "{} が のぼる。" } },
    皮: { write: { written: "かわ", pronounced: "かわ", category: "もの", example: "みかんの {} を むく。" } },
    歯: { write: { written: "はみがき", pronounced: "はみがき", category: "せいかつ", example: "{} を ていねいに する。" } },
    柱: { write: { written: "はしら", pronounced: "はしら", category: "たてもの", example: "いえの {} を 見る。" } },
    祭: { write: { written: "まつり", pronounced: "まつり", category: "ぎょうじ", example: "まちの {} に いく。" } },
    筆: { write: { written: "えんぴつ", pronounced: "えんぴつ", category: "もの", example: "{} を けずる。" } },
    童: { write: { written: "どうわ", pronounced: "どうわ", category: "こくご", example: "{} を よむ。" } },
    畑: { write: { written: "はたけ", pronounced: "はたけ", category: "しぜん", example: "{} で やさいを そだてる。" } },
    緑: { write: { written: "みどり", pronounced: "みどり", category: "しぜん", example: "{} の 木を 見る。" } },
    礼: { write: { written: "おれい", pronounced: "おれい", category: "かいわ", example: "{} を いう。" } },
    詩: { write: { written: "ししゅう", pronounced: "ししゅう", category: "こくご", example: "{} を よむ。" } },
    昔: { write: { written: "むかしばなし", pronounced: "むかしばなし", category: "こくご", example: "{} を きく。" } },
    泳: { write: { written: "すいえい", pronounced: "すいえい", category: "スポーツ", example: "{} を れんしゅうする。" } },
    荷: { write: { written: "にもつ", pronounced: "にもつ", category: "せいかつ", example: "{} を はこぶ。" } },
    炭: { write: { written: "すみ", pronounced: "すみ", category: "もの", example: "{} で 火を おこす。" } },
    丁: { write: { written: "ていねい", pronounced: "ていねい", category: "せいかつ", example: "{} に せつめいする。" } },
    湖: { write: { written: "みずうみ", pronounced: "みずうみ", category: "しぜん", example: "{} に ふねが うかぶ。" } },
    湯: { write: { written: "おゆ", pronounced: "おゆ", category: "せいかつ", example: "{} を わかす。" } },
    箱: { write: { written: "はこ", pronounced: "はこ", category: "もの", example: "{} に しまう。" } },
    豆: { write: { written: "まめ", pronounced: "まめ", category: "たべもの", example: "{} を にる。" } },
    暑: { write: { written: "あつさ", pronounced: "あつさ", category: "せいかつ", example: "なつの {} に まけない。" } },
    氷: { write: { written: "こおり", pronounced: "こおり", category: "しぜん", example: "{} を コップに 入れる。" } },
    寒: { write: { written: "さむさ", pronounced: "さむさ", category: "せいかつ", example: "ふゆの {} に そなえる。" } },
    帳: { write: { written: "てちょう", pronounced: "てちょう", category: "もの", example: "{} に よていを かく。" } },
    拾: { write: { written: "ひろう", pronounced: "ひろう", category: "せいかつ", example: "おちていた ごみを {}。" } },
    漢: { write: { written: "かんじ", pronounced: "かんじ", category: "こくご", example: "新しい {} を おぼえる。" } },
    鼻: { write: { written: "はな", pronounced: "はな", category: "からだ", example: "かぜで {} が つまる。" } },
    皿: { write: { written: "さら", pronounced: "さら", category: "せいかつ", example: "白い {} に くだものを のせる。" } },
    羊: { write: { written: "ひつじ", pronounced: "ひつじ", category: "どうぶつ", example: "まきばに {} が いる。" } },
    笛: { write: { written: "ふえ", pronounced: "ふえ", category: "おんがく", example: "{} を ふく。" } },
  },
};
