module.exports = {
  grade: 1,
  entries: {
    "一": { write: { written: "一つ", pronounced: "ひとつ", category: "thing", example: "りんごが {} ある。" } },
    "右": { write: { written: "右", pronounced: "みぎ", category: "thing", example: "{} の てを あげる。" } },
    "雨": { write: { written: "雨", pronounced: "あめ", category: "nature", example: "{} が ふる。" } },
    "円": { write: { written: "円", pronounced: "えん", category: "thing", example: "100{} を もって いく。" } },
    "王": { write: { written: "王さま", pronounced: "おうさま", category: "person", example: "{} の はなしを よむ。" } },
    "音": { write: { written: "音", pronounced: "おと", category: "nature", example: "{} が きこえる。" } },
    "下": { write: { written: "下", pronounced: "した", category: "thing", example: "つくえの {} を みる。" } },
    "火": { write: { written: "火", pronounced: "ひ", category: "nature", example: "{} を けす。" } },
    "花": { write: { written: "花", pronounced: "はな", category: "nature", example: "{} が さく。" } },
    "貝": { write: { written: "貝", pronounced: "かい", category: "nature", example: "うみで {} を ひろう。" } },
    "学": { write: { written: "学校", pronounced: "がっこう", category: "place", example: "{} へ いく。" } },
    "気": { write: { written: "元気", pronounced: "げんき", category: "abstract", example: "{} に あいさつする。" } },
    "九": { write: { written: "九つ", pronounced: "ここのつ", category: "thing", example: "どんぐりが {} ある。" } },
    "休": { write: { written: "休み", pronounced: "やすみ", category: "time", example: "あしたは {} だ。" } },
    "玉": { write: { written: "玉", pronounced: "たま", category: "thing", example: "{} を ころがす。" } },
    "金": { write: { written: "金", pronounced: "かね", category: "thing", example: "{} を たいせつに しまう。" } },
    "空": { write: { written: "空", pronounced: "そら", category: "nature", example: "{} を みあげる。" } },
    "月": { write: { written: "月", pronounced: "つき", category: "nature", example: "よるの そらに {} が でる。" } },
    "犬": { write: { written: "犬", pronounced: "いぬ", category: "nature", example: "{} が はしる。" } },
    "見": { write: { written: "見る", pronounced: "みる", category: "verb", example: "えほんを {}。" } },
    "五": { write: { written: "五つ", pronounced: "いつつ", category: "thing", example: "みかんを {} ならべる。" } },
    "口": { write: { written: "口", pronounced: "くち", category: "thing", example: "{} を あける。" } },
    "校": { write: { written: "学校", pronounced: "がっこう", category: "place", example: "{} で べんきょうする。" } },
    "左": { write: { written: "左", pronounced: "ひだり", category: "thing", example: "{} に まがる。" } },
    "三": { write: { written: "三つ", pronounced: "みっつ", category: "thing", example: "はこが {} ある。" } },
    "山": { write: { written: "山", pronounced: "やま", category: "nature", example: "{} に のぼる。" } },
    "子": { write: { written: "子ども", pronounced: "こども", category: "person", example: "{} が あそぶ。" } },
    "四": { write: { written: "四つ", pronounced: "よっつ", category: "thing", example: "おさらに {} のせる。" } },
    "糸": { write: { written: "糸", pronounced: "いと", category: "thing", example: "{} を むすぶ。" } },
    "字": { write: { written: "字", pronounced: "じ", category: "thing", example: "{} を ていねいに かく。" } },
    "耳": { write: { written: "耳", pronounced: "みみ", category: "thing", example: "{} で きく。" } },
    "七": { write: { written: "七つ", pronounced: "ななつ", category: "thing", example: "ほしを {} かぞえる。" } },
    "車": { write: { written: "車", pronounced: "くるま", category: "thing", example: "{} に のる。" } },
    "手": { write: { written: "手", pronounced: "て", category: "thing", example: "{} を あらう。" } },
    "十": { write: { written: "十こ", pronounced: "じゅっこ", category: "thing", example: "あめを {} もらう。" } },
    "出": { write: { written: "出る", pronounced: "でる", category: "verb", example: "へやから {}。" } },
    "女": { write: { written: "女の子", pronounced: "おんなのこ", category: "person", example: "{} が わらう。" } },
    "小": { write: { written: "小さい", pronounced: "ちいさい", category: "adjective", example: "{} いぬが いる。" } },
    "上": { write: { written: "上", pronounced: "うえ", category: "thing", example: "たなの {} に おく。" } },
    "森": { write: { written: "森", pronounced: "もり", category: "nature", example: "{} の なかを あるく。" } },
    "人": { write: { written: "人", pronounced: "ひと", category: "person", example: "{} が あつまる。" } },
    "水": { write: { written: "水", pronounced: "みず", category: "nature", example: "{} を のむ。" } },
    "正": { write: { written: "正しい", pronounced: "ただしい", category: "adjective", example: "{} こたえを えらぶ。" } },
    "生": { write: { written: "生える", pronounced: "はえる", category: "verb", example: "めが {}。" } },
    "青": { write: { written: "青い", pronounced: "あおい", category: "adjective", example: "そらが {}。" } },
    "夕": { write: { written: "夕方", pronounced: "ゆうがた", category: "time", example: "{} に いえへ かえる。" } },
    "石": { write: { written: "石", pronounced: "いし", category: "thing", example: "{} を ひろう。" } },
    "赤": { write: { written: "赤い", pronounced: "あかい", category: "adjective", example: "{} はなが さいた。" } },
    "千": { write: { written: "千", pronounced: "せん", category: "thing", example: "{} まで かぞえる。" } },
    "川": { write: { written: "川", pronounced: "かわ", category: "nature", example: "{} で さかなを みる。" } },
    "先": { write: { written: "先", pronounced: "さき", category: "thing", example: "れつの {} に ならぶ。" } },
    "早": { write: { written: "早い", pronounced: "はやい", category: "adjective", example: "{} じかんに おきる。" } },
    "草": { write: { written: "草", pronounced: "くさ", category: "nature", example: "{} を つむ。" } },
    "足": { write: { written: "足", pronounced: "あし", category: "thing", example: "{} が はやい。" } },
    "村": { write: { written: "村", pronounced: "むら", category: "place", example: "{} に すむ。" } },
    "大": { write: { written: "大きい", pronounced: "おおきい", category: "adjective", example: "{} こえで よむ。" } },
    "男": { write: { written: "男の子", pronounced: "おとこのこ", category: "person", example: "{} が はしる。" } },
    "竹": { write: { written: "竹", pronounced: "たけ", category: "nature", example: "{} で できた かごを もつ。" } },
    "中": { write: { written: "中", pronounced: "なか", category: "thing", example: "はこの {} を みる。" } },
    "虫": { write: { written: "虫", pronounced: "むし", category: "nature", example: "はっぱに {} が いる。" } },
    "町": { write: { written: "町", pronounced: "まち", category: "place", example: "{} を あるく。" } },
    "天": { write: { written: "天気", pronounced: "てんき", category: "time", example: "{} の よい ひだ。" } },
    "田": { write: { written: "田", pronounced: "た", category: "place", example: "{} に みずが はいる。" } },
    "土": { write: { written: "土", pronounced: "つち", category: "nature", example: "{} で だんごを つくる。" } },
    "二": { write: { written: "二つ", pronounced: "ふたつ", category: "thing", example: "りんごを {} もらう。" } },
    "日": { write: { written: "日", pronounced: "ひ", category: "time", example: "きょうは よい {} だ。" } },
    "入": { write: { written: "入る", pronounced: "はいる", category: "verb", example: "へやに {}。" } },
    "年": { write: { written: "年", pronounced: "とし", category: "time", example: "ことしは よい {} に したい。" } },
    "白": { write: { written: "白い", pronounced: "しろい", category: "adjective", example: "ゆきは {}。" } },
    "八": { write: { written: "八つ", pronounced: "やっつ", category: "thing", example: "おさらを {} ならべる。" } },
    "百": { write: { written: "百", pronounced: "ひゃく", category: "thing", example: "{} まで かぞえる。" } },
    "文": { write: { written: "文", pronounced: "ぶん", category: "book", example: "みじかい {} を よむ。" } },
    "木": { write: { written: "木", pronounced: "き", category: "nature", example: "{} に のぼる。" } },
    "本": { write: { written: "本", pronounced: "ほん", category: "book", example: "{} を よむ。" } },
    "名": { write: { written: "名前", pronounced: "なまえ", category: "thing", example: "{} を かく。" } },
    "目": { write: { written: "目", pronounced: "め", category: "thing", example: "{} を とじる。" } },
    "立": { write: { written: "立つ", pronounced: "たつ", category: "verb", example: "いすから {}。" } },
    "力": { write: { written: "力", pronounced: "ちから", category: "abstract", example: "{} を あわせる。" } },
    "林": { write: { written: "林", pronounced: "はやし", category: "nature", example: "{} を ぬける。" } },
    "六": { write: { written: "六つ", pronounced: "むっつ", category: "thing", example: "えんぴつが {} ある。" } },
  },
};
